name: ebono_pos
description: "Ebono POS."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.5.2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dropdown_search: ^6.0.1
  flutter_svg: ^2.0.16
  printing: ^5.13.4
  libserialport: ^0.3.0+1
  digital_scale: ^1.0.1+6
  pdf: ^3.11.1
  intl: ^0.19.0
  flutter_styled_toast: ^2.2.1
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  connectivity_plus: ^3.0.3
  lottie: ^3.1.3
  flutter_window_close: ^1.2.0
  window_manager: ^0.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_client_sse: ^2.0.3
  path_provider: ^2.0.2
  dropdown_button2: ^2.3.9
  audioplayers: ^6.1.0
  package_info_plus: ^8.1.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/
    - assets/lottie/
    - assets/audio/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
